### ISSUE TITLE
Unable to add Users on the site where CRM app is installed

### ISSUE THREAD

**Issue by vinodkumarkolli** [frappe/crm#788]
I have CRM app installed on my site and I recently updated the site
**Versions**
======
Frappe CRM: v2.0.0-dev (develop)
Frappe Framework: v15.66.1 (version-15)

When I am creating a new user or updating a new user, site started throwing error saying - 
ModuleNotFoundError: No module named 'frappe.utils.modules'
Possible source of error: crm (app)

I am attaching the complete log
`### Route
```
Form/User/xxxxxxx@gmail.com
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 115, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1739, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 378, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 414, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1130, in run_before_save_methods
    self.run_method("before_validate")
  File "apps/frappe/frappe/model/document.py", line 1007, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1364, in composer
    hooks.append(frappe.get_attr(handler))
  File "apps/frappe/frappe/__init__.py", line 1729, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1439, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/crm/crm/api/__init__.py", line 6, in <module>
    from frappe.utils.modules import get_modules_from_all_apps_for_user
ModuleNotFoundError: No module named 'frappe.utils.modules'
`
Can someone help me fix this error?? I am unable to add any user in my PROD environment
Thanks in advance

**Comment by shariquerik** [comment]
@vinodkumarkolli This is already fixed in the latest version upgrade to latest version

**Comment by vinodkumarkolli** [comment]
@shariquerik I tried 
`$bench update --reset`
but it is still throwing same error. 

![Image](https://github.com/user-attachments/assets/3d13cbc9-1053-49b2-9d0c-b449de05a9c5)
